### ISSUE TITLE
Open (and pin) calendar as an independent pain.

### ISSUE THREAD

**Issue by psyguy** [liamcain/obsidian-calendar-plugin#29]
Hi Liam,
Thanks for the wonderful plugin!

It would be nice if the calendar could be opened as an independent pain, the same way as the Graph view (and local graph view) can be opened in new pain.

This way, one can have it always open (and pin it to the workspace) and would not require the whole left sidebar to be expanded. (I am using Obsidian on a vertical screen and opening the left sidebar takes virtually 30% of the space 😅.)

**Comment by liamcain** [comment]
Hi @psyguy, this should actually be possible if you have v1.2.0 installed.

You can update from within the app by going to the community plugin page and clicking "update."

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/693981/98243179-93e93d80-1f3b-11eb-9504-15242b392d93.png">

Note: you will need to restart Obsidian for the update to take effect.

**Comment by psyguy** [comment]
It was up-to-date, but I didn't know I could drag and drop the calendar to a new pain, nice!
(IMHO, this plugin could benefit from a bit more documentation 😉.)

Is it also possible to change the font size, so it takes less space?

**Comment by liamcain** [comment]
The plugin is fully customizable via CSS if you're comfortable making changes to your `obsidian.css` file in the vault.

If you just want to make things smaller, you could add something like this:

```css
/* obsidian-calendar-plugin */
/* https://github.com/liamcain/obsidian-calendar-plugin */
#calendar-container .title {
  font-size: 0.9em;
}

#calendar-container .arrow svg {
  height: 12px;
  width: 12px;
}

#calendar-container .table {
  font-size: 0.8em;
}
```
