### ISSUE TITLE
Weekend Background-Color without rounded corners?

### ISSUE THREAD

**Issue by boris-df** [liamcain/obsidian-calendar-plugin#363]
I'm aware that i can color the background of the weekend days in two ways:
a) with 

```
#calendar-container {
  --color-background-weekend: #eeeeee;
```

or b) with 
```
#calendar-container .weekend {
  background-color: var(--background-primary-alt);
}
```

This works, but there are rounded corners around each day.
![image](https://github.com/liamcain/obsidian-calendar-plugin/assets/49982409/3d2e5761-7019-4e97-bd41-c0af4a78d411)

Is there a way to make the weekend look like a solid "rectange"? For example, remove the corner-radius from the weekend-days (if they doesn't have any margins it should look as solid area then)?

(i'm using the "Minimal"-Theme if this makes a difference)

Oh, and for the screenshot if someone asks how i made the "Today" having a background-Color: I changed that like this (because with the default settings and the "Minimal"-Theme i could hardly see the "Today"

```
#calendar-container .today {
  color: var(--background-primary);
  background-color: var(--interactive-accent);
  font-weight: 600;
}
#calendar-container .today .dot {
  fill: var(--interactive-accent);
}

#calendar-container .weekend {
  background-color: var(--background-primary-alt);
}
```

**Comment by believer** [comment]
This is related to the minimal theme. I've fixed it by removing the border radius from the last two table cells.

```css
/* Remove the border radius from the second-to-last and last cells in the calendar. */
#calendar-container tr td:nth-last-child(2),
#calendar-container tr td:last-child {
  border-radius: 0;
}
```

Note that you may need to adjust the selectors if your week does not start on Monday.
