### ISSUE TITLE
Arrows (Buttons) and Today Button are all together

### ISSUE THREAD

**Issue by MichaelLepori** [liamcain/obsidian-calendar-plugin#369]
### Describe the bug
Arrows, Buttons and Today Button all together. Forward and Today can I click (not easy, but it is possible). To Go back, that doesn't work.

### Expected behavior
As you see in the screenshot are the button <, Today and > all together.

### Screenshots
![image](https://github.com/liamcain/obsidian-calendar-plugin/assets/39479918/9d13b137-db20-41be-894e-6238b47a1968)

#### OS
Windows 10 22H2

### Theme:
Plugin Mininal Theme → Tried to put it on Inactive → Same error.
I tried also to deactivate all my CSS Add-ons. Nothing changed.

Do you have any Idea, how I can fix this?

Thank you very much for your Time and for your great Plugin!

**Comment by padowi** [comment]
@MichaelLepori : do you by any chance have the media notes plugin installed and activated?
And if so, does it help to comment out the following CSS instruction:

```css
.arrow {
        position: absolute;
        bottom: 0;
        margin-left: 0px;
        width: 24px;
        height: 24px;
        background-size: contain;
        opacity: 0.8;
        top: 23px;
}
```

inside .obsidian/plugins/media-notes/style.css ?

Edit to add: 
Because this has helped me.
