### ISSUE TITLE
Variable for year color

### ISSUE THREAD

**Issue by zalenza** [liamcain/obsidian-calendar-plugin#45]
I might be missing something, but there doesn't seem to be a separate variable for changing the color of the year. Matching the theme accent color is a little too eye-catching for me. 

Thanks for a great plugin!

**Comment by liamcain** [comment]
You're right, there's no separate variable but you can target the CSS class. Example:

```css
#calendar-container .year {
  color: red;
}
```

I'll add this to the README!
