### ISSUE TITLE
Bold headers

### ISSUE THREAD

**Issue by DutchPete** [liamcain/obsidian-calendar-plugin#63]
I am using your plug-in (1.4.2), and have customized it a bit. The only thing I cannot figure out is how to make the header text (i.e. the weekday names, like Mon, Tue, etc.) bold.

I tried:
```css
#calendar-container .text-header {
  color: var(--base2);
  font-weight: bold;
}
```

and also with `.header` instead of `text-header` but it does not work.
Please advise.

**Comment by liamcain** [comment]
To make the title bold, you can add:

```css
#calendar-container .title .month, 
#calendar-container .title .year {
  color: var(--base2);
  font-weight: bold;
}
```

**Comment by DutchPete** [comment]
I already have those. I mean the names of the week days, such a Mon, Tue, Wed, etc.

**Comment by liamcain** [comment]
Oh, sorry about that! I didn't read the initial question clearly enough. To bold the days of the week, you want to just target the `<th>` so:

```css
#calendar-container th {
  font-weight: bold;
}
```

**Comment by DutchPete** [comment]
Liam, thank you, that makes sense, unfortunately it does not seem to affect those weekday names 1 iota.

I say "seems" because when I use values, there is a change. E.g. 500 makes them visibly thinner, at 900 they are back to what they were before. So, I have the impression that the font-weight as it is in your default plug-in is already bold for the weekday headers.

**Comment by DutchPete** [comment]
Liam, sorry to disturb you again, but something strange has happened. I cannot change anything anymore, and colors are shifted.

<img width="399" alt="cal" src="https://user-images.githubusercontent.com/10794265/101245398-47994500-3715-11eb-9386-b4071bb5f979.png">

This is the code I have for the calendar:

```css
/* Calendar plug-in */
#calendar-container {
  --color-text-heading: var(--base3);
}

#calendar-container .today {
  color: var(--base2);
  font-weight: bold;
}

#calendar-container .week-num {
  color: var(--base2);
  font-weight: bold;
}

#calendar-container .week-num:hover {
  color: var(--base5);
  font-weight: bold;
}

#calendar-container .month {
  color: var(--base2);
  font-weight: bold;
}

#calendar-container .year {
  color: var(--base3);
  font-weight: 300;
}

#calendar-container th {
  font-weight: bold;
}
```

base 2 is green, and base 3 is dark grey. In the month and year they are exchanged.
Furthermore, the week numbers are not bold anymore, and neither is today's date.
Also, week 49 is active, its background is green (as it should be, and when I hover it should be a lighter shade of green (base 5) but it is purple.

I have not done anything other than try to make the week day headers bold as per your last comment. I am stunned.
